# 模型配置
model:
  pretrained_model: "/Users/fufu/.cache/modelscope/hub/answerdotai/ModernBERT-large"
  hidden_size: 1024
  intermediate_size: 4096
  num_hidden_layers: 24
  num_attention_heads: 16
  max_position_embeddings: 8192
  classifier_dropout: 0.1
  num_labels: 3
  num_relations: 53
  entity_types: ["疾病", "症状", "检查", "手术", "药物", "其他治疗", "部位", "社会学", "流行病学", "预后", "其他"]
  position_embedding_type: "alibi"  # 使用 ALiBi 位置编码
  use_cache: false  # 训练时禁用缓存
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  vocab_size: 50368

# 训练配置
training:
  batch_size: 8
  eval_batch_size: 8
  learning_rate: 1.0e-5  # 降低学习率
  weight_decay: 0.1  # 增加权重衰减
  num_train_epochs: 50
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  logging_steps: 10

# 数据配置
data:
  train_file: "./data/CMeIE_train.json"
  eval_file: "./data/CMeIE_dev.json"
  schema_file: "./data/53_schemas.jsonl"
  max_seq_length: 512

# 设备配置
device:
  use_cuda: true
  use_mps: true

# 输出配置
output:
  output_dir: "./outputs"
  save_total_limit: 3
  load_best_model_at_end: true
