# 模型配置
model:
  model_name_or_path: "/Users/fufu/Downloads/modern_bert_multilingual"
  num_labels: 3
  num_relations: 53
  entity_types: ["疾病", "症状", "检查", "手术", "药物", "其他治疗", "部位", "社会学", "流行病学", "预后", "其他"]
  use_cache: false

# 训练配置
training:
  # 基础训练参数
  batch_size: 2
  eval_batch_size: 2
  num_train_epochs: 10
  gradient_accumulation_steps: 16  # 增加梯度累积步数，相当于 batch_size=32
  
  # 优化器参数
  learning_rate: 5e-6  # 降低学习率
  weight_decay: 0.01
  max_grad_norm: 10.0  # 保持梯度裁剪阈值
  warmup_ratio: 0.35  # 增加预热比例
  
  # 损失函数配置
  use_weighted_loss: true  # 使用静态类别权重
  
  # 其他配置
  logging_steps: 100
  eval_ratio: 0.1
  random_seed: 42
  freeze_backbone: false

# 数据配置
data:
  train_file: "./data/CMeIE_train_with_idx.jsonl"
  schema_file: "./data/53_schemas.jsonl"
  max_seq_length: 1024

# 输出配置
output:
  output_dir: "./outputs"
  save_checkpoint_epochs: 5
  plot_metrics:
    enabled: true

# 评估配置
evaluation:
  eval_steps: 100
