# 模型配置
model:
  model_name_or_path: "/Users/fufu/Downloads/modern_bert_multilingual"
  use_cache: false

# 训练配置
training:
  batch_size: 2
  num_epochs: 10
  learning_rate: 5e-6
  weight_decay: 0.01
  max_grad_norm: 10.0
  warmup_ratio: 0.35
  eval_ratio: 0.2
  random_seed: 42

# 数据配置
data:
  train_file: "./data/CMeIE_train_with_idx.jsonl"
  schema_file: "./data/53_schemas.jsonl"
  max_seq_length: 1024

# 输出配置
output:
  output_dir: "./outputs"
