# 模型配置
model:
  model_name_or_path: "/Users/fufu/.cache/modelscope/hub/answerdotai/ModernBERT-large"
  num_labels: 3
  num_relations: 53
  entity_types: ["疾病", "症状", "检查", "手术", "药物", "其他治疗", "部位", "社会学", "流行病学", "预后", "其他"]
  use_cache: false

# 训练配置
training:
  # 批次大小
  batch_size: 2
  eval_batch_size: 2
  
  # 优化器参数
  weight_decay: 0.01    # 权重衰减系数
  max_grad_norm: 10.0   # 梯度裁剪阈值
  
  # 学习率调度
  learning_rate: 5.0e-5  # 调整为建议的基准学习率
  warmup_ratio: 0.1     # 预热比例，10%步数用于预热
  
  # 训练控制
  num_train_epochs: 50
  logging_steps: 10
  use_weighted_loss: true
  eval_ratio: 0.1
  random_seed: 42
  freeze_backbone: false
  gradient_accumulation_steps: 1

# 数据配置
data:
  train_file: "./data/CMeIE_dev.json"
  schema_file: "./data/53_schemas.jsonl"
  max_seq_length: 1024

# 输出配置
output:
  output_dir: "./outputs"
  save_checkpoint_epochs: 5
  plot_metrics:
    enabled: true

# 评估配置
evaluation:
  eval_steps: 100
